apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kvib-one-poi-map-app-dev
  annotations:
    argocd/app-name: kvib-one-poi-map-app-dev
    backstage.io/kubernetes-id: kvib-one-poi-map-app
    backstage.io/kubernetes-namespace: kvib-one
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/kvib-one-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/kvib-one/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/kvib-one/deployments/kvib-one-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/kvib-one-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://kvib-one-poi-map-app-kvib-one.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-kvib-one
  consumesApis:
    - gateway-api-kvib-one
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-kvib-one
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
